### PR TITLE
Revert "tidy up definition of owner in funding"

### PR DESCRIPTION
**Pull request by edbennett**
Reverts M4rkD/cogs3#2

Looks like we missed something—this causes a regression where users can now approve their own funding sources. The previous definition correctly prevents users approving their own projects, although it does leave edbennett#87 unresolved.

### CODE REVIEW

**Comment by markgdawson** [comment]
Good catch! Definitely not what we where trying to accomplish here. 

Silly question. What if we put self.pi on both? Is that another possible option?

**Comment by markgdawson** [comment]
@edbennett - I've had another look. I think the intention here was to keep self.pi for both cases (rather self.created_by) as self.owner.

It seems better to me to keep things consistent between sites when possible.

I've tried to do this on the web interface but only succeeded in creating a branch and PR on your repo!

**Comment by markgdawson** [comment]
@edbennett I've put a new change in, does this resolve the problem?

**Comment by edbennett** [comment]
While this doesn't matter for us for now, this breaks when an institution has the funding workflow but not funding approval. In this case, emails should not be sent and users should be able to manage all attributions that they have created.

(The original logic, I believe, was there to cover both cases, although did so in a very cryptic manner.)

**Comment by markgdawson** [comment]
I'm going to close this without merge and pull the change directly into current master.

**Pull request closed without merging**
