### PR TITLE
use a manual filter rather than relying on the Model in AttributionListView

### LINKED ISSUE #86: Error thrown on when "funding sources" selected from dropdown in funding sources index
Error thrown by endpoint:
http://localhost:8000/en-gb/funding/list/fundingsources/

Seems like the route might be missing

### PR DESCRIPTION
**Pull request by edbennett**
inheritance issues caused this to fail due to availability of field definitions on models.

this fixes edbennett#86

### CODE REVIEW

**Comment by markgdawson** [comment]
Good catch on this one. Mind you, Django generic views are so ugly sometimes. Good effort to hide the warts.

Not sure if you can get away without calling super mind? But don't trust me on it, I might be wrong.

In that case you could maybe specialise a method for each class, like:

class Attrib():
  def _get_queryset():
    % specialise this function for the query

  def get_queryset():
    queryset = self._get_queryset()
    owned_set = queryset.filter(owner=user)
  
 class Pub():
  def _get_queryset():
    % specialised function for child

but that's the best I've got and it still hurts my eyes.

Up to you if you want to leave it or tweak it. Let me know either way and I'll push it.

**Comment by edbennett** [comment]
I must be missing something—surely since `get_queryset()` will be defined on `AttributionListView`, the call from `AttributionListView._get_queryset()` will still need to call `super()` to avoid getting the local one? Or is that not the `super()` call you were looking to work around?

**Comment by markgdawson** [comment]
You're completely right of course. Refactoring as I above does nada to avoid a calls to super. It's my fault, I mixed two ideas together.

Idea 1, I don't think you need to call super. I think you can just override get_queryset method to return the query result. So rather than:

```
class SomeClass:
  def get_queryset(self):
     q = super().get_queryset(self)
     return q.filter(filte on some criteria something)
```
I think you can just do:
```
class SomeClass:
  def get_queryset(self):
     return SomeClass.objects.get(name='Mark')
```
Which gives you one less constraint on how you need to write the code, and might help you simplify it slightly.

Second idea, what could you do if we wanted to refactor the code (given that we have fewer constraints). I made a little suggestion, I'll be honest, I can think of a good number of solutions that are equally good, and you might be able to think of something that's better.

Just to avoid calling something "good" without motivation, I'm looking specifically at the coupling between object instances, and making that as explicit and obvious as possible. I have a preference for function calls over instance variables, because to my mind a function call is more obviously part of the object interface, but it's python - so that's super-debatable.

You'd be right to say "come on Mark, this is just a glorified configuration language that looks like OOP, we don't need to care". And I'd tell you you're right. We don't need to care.

I'm going for the approach of reviewing as best I can, but I'm not telling you to change it. I'm just throwing some ideas at you. :smile:

**Comment by edbennett** [comment]
Using `super()` is a pattern used elsewhere in the site and in the documentation; I'm guessing so that if classes are composed at a later date then query sets don't accidentally get squashed. Otoh, I can't see anything getting added between this and `generic.ListView` that would manipulate the query set. However, at this point you're fighting with the very nature of Django's class-based views; the `Model` instance variable no longer does what any experienced Django dev would think it will do, so you end up building your own custom stack on top of Django that will confuse experienced Django devs and leave inexperienced Django devs unable to Google how to work with it.

Using function calls instead of state I could do something like 

```
class AttributionListView(LoginRequiredMixin, generic.ListView):
    context_object_name = 'attributions'
    template_name = 'funding/list.html'
    paginate_by = 10

    def _get_queryset(self, model):
        user = self.request.user
        queryset = model.objects.all()
        owned_set = queryset.filter(owner=user)
        user_set = queryset.filter(fundingsource__in=FundingSource.objects.filter(
            fundingsourcemembership__user=user,
            fundingsourcemembership__approved=True,
        ))
        return (owned_set | user_set).order_by('-created_time')

    def get_queryset(self):
        return _get_queryset(self, Attribution)

class PublicationListView(AttributionListView):
    def get_queryset(self):
        return _get_queryset(self, Publication)


class FundingSourceListView(AttributionListView):
    def get_queryset(self):
        return _get_queryset(self, FundingSource)
```

That does remove the nastiness with creating the dict to be able to pass in an arbitrary kwarg to `filter`, but at the expense of wetness in all three classes, since I now have to keep adding boilerplate to define `get_queryset`, and the difference between them is buried in the function arguments.

Net ugliness is probably down slightly, but again at the expense of being idiomatic to the framework we're developing against.

(I honestly don't have enough OOP experience to have a good intuition for what "good OOP" and "bad OOP" look like, hence relying on opinionated libraries to make the decisions for me.)

**Pull request merged**
